Redesign
Financial-Times/o-labels pull request #8
Opened 2016-10-07 16:37 UTC by quarterto

Needs design review. Do the new states and colours make sense? This is technically semver-major since the semantics and format of `$o-labels-states` have changed, but it was never documented and I'd be willing to bet nobody used it.

New hotness:

![screenshot 2016-10-07 17 34 16](https://cloud.githubusercontent.com/assets/631757/19197908/4c3c79ca-8cb4-11e6-846d-51c0867a90d2.png)
![screenshot 2016-10-07 17 34 08](https://cloud.githubusercontent.com/assets/631757/19197907/4c33c62c-8cb4-11e6-9263-6499341abb37.png)

Old and busted:

![screenshot 2016-10-07 17 35 01](https://cloud.githubusercontent.com/assets/631757/19197928/63c449a6-8cb4-11e6-8c7c-268a203a0060.png)

2016-10-21 11:12 UTC, JakeChampion commented on scss/_states.scss
> +		@include oColorsSetUseCase(o-labels-#{$state}, $usecase, $palette);
Real nice! 👍

2016-10-21 11:13 UTC, JakeChampion approved these changes

2016-10-21 13:03 UTC, onishiweb requested changes

2016-10-21 13:03 UTC, onishiweb commented on scss/_mixins.scss
> +	@if not $_o-labels-warned-size and ($size == 'medium' or $size == 'big') {
Was this a design decision to use `o-typography` and remove the label sizing?

2016-10-21 13:08 UTC, onishiweb commented
I'm not sure about it being a major release? Is there anything in it that will break existing labels apart from the update their styling?

Also, has this been through design review yet?

Thanks for the PR :)

2016-10-21 13:19 UTC, quarterto commented
If anyone were using `$o-labels-states` this would be breaking, but I'm pretty sure I'm the only user of this module, and I don't use it.

I'm going to find a designer to review it this afternoon.

2016-10-21 13:28 UTC, onishiweb commented
Cool, thanks. Ok, in that case it's breaking, just in case someone other than you is using it.

2016-10-24 14:53 UTC, quarterto commented
Sue's happy with the new design, agrees with the o-typography sizing @onishiweb

2016-10-24 15:18 UTC, onishiweb approved these changes

2016-10-24 15:19 UTC, merged

2020-07-13 13:30 UTC, chee commented
yes i think the colours make sense